In [1]:
import numpy as np

In [9]:
# implementing lasso regression

class Lasso_regression():
    # initiating the hyper parameters
    
    def __init__(self,learning_rate, no_of_iteration, lambda_parameter):
        self.learning_rate = learning_rate
        self.no_of_iteration = no_of_iteration
        self.lambda_parameter = lambda_parameter

    # fitting the dataset to the model
    def fit(self,X,Y):
        # m --> no.of data points --> no. of rows
        # n --> no. of input features --> no.of columns
        # we need to find the shape of X
        
        self.m,self.n = X.shape
        self.w = np.zeros(self.n)
        self.b = 0
        self.X = X
        self.Y = Y
        
        # implementing gradient descent algorithm for optimization
        for i in range(no_of_iteration):
            self.update_weight()

    def update_weight(self):
        
        # linear equation of the model
        Y_prediction = self.predict(self.X)

        # gradient of weight 
        dw = np.zeros(self.n)
        for i in range(self.n):
            if self.w[i]>0:
                dw[i] = (-(2*(self.X[:,i].dot(self.Y-Y_prediction)) + self.lambda_parameter)/self.m)

            else:
                dw[i] = (-(2*(self.X[:,i].dot(self.Y-Y_prediction)) - self.lambda_parameter)/self.m)

    
        # gradient of bias
        db = (-2 * np.sum(self.Y - Y_prediction))/self.m

        # updating weight and bias
        self.w = self.w - self.learning_rate*dw
        self.b = self.b - self.learning_rate*db

    def predict(self,X):
        return X.dot(self.w)+self.b


In [10]:
# Sample dataset
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])  # Feature vectors
Y = np.array([3, 6, 8, 10])  # Target values

# Hyperparameters
learning_rate = 0.01
no_of_iteration = 1000
lambda_parameter = 0.1

In [18]:
# Create an instance of your Lasso_Regression class
lasso_model = Lasso_regression(learning_rate, no_of_iteration, lambda_parameter)

# Fit the model to the dataset
lasso_model.fit(X, Y)

# Make predictions
predictions = lasso_model.predict(X)

print("Predictions:", predictions)

Predictions: [ 3.29657834  5.60044585  7.90431337 10.20818089]


In [20]:
lasso_model.predict(np.array([[5,6]]))

array([12.5120484])

In [21]:
import pandas as pd

In [22]:
df=pd.read_csv('salary_data.csv')


In [24]:
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [28]:
from sklearn.model_selection import train_test_split
X = df['YearsExperience']
Y = df['Salary']
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)
x_train = x_train.values.reshape(-1, 1)


In [29]:
model = Lasso_regression(learning_rate,no_of_iteration,lambda_parameter)
model.fit(x_train,y_train)


In [31]:
x_test = x_test.values.reshape(-1,1)
pred = model.predict(x_test)

In [32]:
pred

array([ 40418.77877149, 122970.10036321,  64808.94196904,  62932.77556923,
       115465.43476396, 107960.76916472])

In [33]:
x_test

array([[ 1.5],
       [10.3],
       [ 4.1],
       [ 3.9],
       [ 9.5],
       [ 8.7]])

In [34]:
df

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [35]:
from sklearn.metrics import r2_score
r2_score(y_test,pred)

0.9889623462116203

In [36]:
from sklearn.linear_model import Lasso
reg = Lasso(alpha=0.1)
reg.fit(x_train,y_train)

Lasso(alpha=0.1)

In [37]:
pred = reg.predict(x_test)

In [38]:
r2_score(pred,y_test)

0.9864824709983808

In [39]:
from sklearn.metrics import mean_squared_error

In [41]:
l=mean_squared_error(y_test,pred)

In [42]:
np.sqrt(l)

3581.000245954363